layout_spectrum: 0.6902459587436169
typography_spectrum: 0.9098497675731778
color:
  brandStrength: 0.5296447700820863
  lightness: 0.525525730336085
  saturation: 0.13961351360194385
  rhythmicContrast: 0.1805701944977045
  brandColors:
    - '#A3D9CD'
    - '#FFFEFE'
    - '#BAE2DA'
    - '#EAF6F4'
    - '#D9EFEB'
name: anicetephoto
navigation:
  - name: '@anicetephoto'
    url: 'https://www.instagram.com/anicetephoto/'
    type: external
